version: '2'
services:
  squidex-build:
# Use custom aspnet images where phantomjs is installed
    build: tools/aspnetcore-build-phantomjs
    volumes:
      - .:/sln
    working_dir: /sln
# Run the build script on local folder
    entrypoint: ["sh", "./build.sh"]